spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-nisha91-nisha91-khairi.aivencloud.com}:${DB_PORT:25211}/defaultdb?sslMode=REQUIRED&allowPublicKeyRetrieval=true
    username: ${avnadmin}
    password: ${AVNS_1sh-uZgjxSwHL62m3yW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true